### ISSUE TITLE
Check the render method of `TwentyFourHoursMode`.

### ISSUE THREAD

**Issue by quanixstudio** [ecmadao/react-times#104]
Error:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `TwentyFourHoursMode`.
    in TwentyFourHoursMode (created by AsyncComponent)
    in AsyncComponent (created by MaterialTheme)
    in div (created by MaterialTheme)
    in MaterialTheme (created by AsyncComponent)
    in AsyncComponent (created by TimePicker)
    in div (created by OutsideClickHandler)
    in OutsideClickHandler (created by TimePicker)
    in div (created by TimePicker)
    in TimePicker

Code:
import React from 'react';
import ReactDOM from 'react-dom';
import TimePicker from 'react-times';
import 'react-times/css/material/default.css';

ReactDOM.render(<TimePicker />, document.getElementById('app'));

Also tried by adding parameters to use 12 hours but then the error changes to

Check the render method of `TwelveHoursMode`.

**Comment by quanixstudio** [comment]
Updating some of my dependencies already fixed it.

**Comment by rizwan-ishtiaq** [comment]
I am facing the same issue, how you fixed it?
I am trying this component 1st time.

**Comment by ecmadao** [comment]
@rizwan-ishtiaq
hi, maybe you can check your react version
