### ISSUE TITLE
增加class

### ISSUE THREAD

**Issue by BryantZhou** [ecmadao/react-times#13]
可以在OutsideClickHandler的render里面那个div加一个class吗 这样的话就可以对那个时钟做更多的样式布局

**Comment by ecmadao** [comment]
@BryantZhou 
意思是，加一个例如是 `.outside_container` 的class，之后可以将不同样式写在不同CSS文件里，但每个文件都基于父组件`.outside_container`，比如：

```css
.outside_container .material_theme {}
```

```css
.outside_container .classic_theme {}
```

不知道我理解的对不对？

**Comment by BryantZhou** [comment]
例如我想把你的时钟做一个masker出现  在页面居中 这时候我需要做一个深灰的半透明底色 发现那个时钟父级的div没有任何的class  我想在自己的css覆盖你本来的样式 也没有地方可以入手  又不想用js增加class上去

**Comment by ecmadao** [comment]
@BryantZhou 
理解了，已增加class`outside_container`，更新版本至V1.2.8
之后也打算给时钟增加更多主题，有什么想法可以及时沟通喽

**Comment by BryantZhou** [comment]
好的 ok
