### ISSUE TITLE
request for feature: move to selecting minute just after choosing hour

### ISSUE THREAD

**Issue by thg303** [ecmadao/react-times#19]
I think it would be great if user would be moved to selecting minutes after choosing hour. For me it took a couple of seconds to find out I have to click on the minutes on top and then actually pick the minutes.
at-least we can have it as a configuration like "focused". what do you think?

**Comment by ecmadao** [comment]
@thg303 
This feature seems quite reasonable. I'll work on it later.

**Comment by thg303** [comment]
actually I implemented it. I just wonder should it be on "feature optimize" branch?

**Comment by ecmadao** [comment]
@thg303 
Great, you can use whatever branch as you like. How about create a new PR?

**Comment by thg303** [comment]
cool, I submitted the PR. @ecmadao

**Comment by ecmadao** [comment]
merged. It had some conflict with master branch and I already solved. So I delete others old branch, and we'd better create new branch to dev.

**Comment by thg303** [comment]
great thank you
