### ISSUE TITLE
Add more props for picker

### ISSUE THREAD

**Issue by NgKhanh** [ecmadao/react-times#25]
This is nice picker, but I hope you can consider to fix somethings:

1. Add props  (open=true/false) to show picker on render without click button
2. Remove time on picker_pointer_drag when dragging, it's keeps old value on dragging seem make no sense
3. TwelveHoursMode
- picker not close after select time, should has a ok button to close(user'll dont know click around to close)
- minute_pointer_drag should only drag to minute (now it can be drag to point_wrapper)
4. Allow custom AM|PM in other languages

**Comment by ecmadao** [comment]
@NgKhanh 
Sorry to reply you so late, I'm too busy working for a project these days.
I think your opinions are helpful and interesting, I'll work for them this week or later. Besides, you can also fork master branch and create a pull request. If you have any other ideas, maybe we can discuss in this issue together. Thanks again!

**Comment by plysik** [comment]
How about adding custom renderer for classic theme modal?
