### ISSUE TITLE
Malfunction on pointer selection.

### ISSUE THREAD

**Issue by cusspvz** [ecmadao/react-times#28]
Sometimes component allows a selection of:
* 60 on the minutes pointer when dragging.
* 24 on the hours pointer when dragging.

**Comment by ecmadao** [comment]
@cusspvz 
Cool. I'll fix them later.
THX!

**Comment by ecmadao** [comment]
@cusspvz 
Fixed. Thanks again!

**Comment by cusspvz** [comment]
Thank you! ;)
Great work by the way! 🔝
