### ISSUE TITLE
timeMode 12 does not seems to work

### ISSUE THREAD

**Issue by githubdoramon** [ecmadao/react-times#29]
When I set the timeMode to 12 in the classic mode I can't get the dropdown to show the time options in 12 hour mode, only in 24

**Comment by ecmadao** [comment]
@githubdoramon 
Sorry to reply you late, but I seems can not find the bug. Can you describe it more clearly? Thanks a lot!

**Comment by githubdoramon** [comment]
When I set the timeMode to 12 (instead of 24), the dropdown options keep appearing as 24 hour mode (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24), instead of 12 hour mode (12pm,1am,2am,3am,4am,5am,6am,7am,8am,9am,10am,11am,12am,1pm, etc...)

**Comment by ecmadao** [comment]
@githubdoramon 
Are you using the classic theme ?

**Comment by githubdoramon** [comment]
Ops.... forgot to mention that.... Yes, classic!

2017-03-23 8:45 GMT-03:00 ecmadao <notifications@github.com>:

**Comment by ecmadao** [comment]
@githubdoramon 
Got it. Infract I forgot add 12 hours timemode for classical theme 😂
I'll add it as soon as possible (about few hours later ).

**Comment by githubdoramon** [comment]
Thanks a lot... And feel free to create another repository with the date version of your library :) hehehehe

**Comment by ecmadao** [comment]
@githubdoramon 
Cool😁.
And I have add 12 mode for classic theme, which already published to v1.4.2, you can update and try it. It's my pleasure to receive any issues or pull request. THX!
