### ISSUE TITLE
autoMode with 12 hour timeMode

### ISSUE THREAD

**Issue by erin-doyle** [ecmadao/react-times#33]
Is autoMode intended to work with 12 hour timeMode or is it only supposed to work with 24 hour timeMode?  It would be great to have that as an option for both as well as some documentation around the property.

**Comment by ecmadao** [comment]
Both supported. You can check online demo here [https://ecmadao.github.io/react-times](https://ecmadao.github.io/react-times/?selectedKind=TwelveHoursMode&selectedStory=focused%20at%20setup&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) to see them.

**Comment by erin-doyle** [comment]
I don't see an example of a 12 hour mode picker showing what I thought was the expected behavior from autoMode.  Maybe I'm not clear on what autoMode is supposed to do?  I was expecting that the user would be forced to select the hour value and then after click on hour be presented with the options to select the minutes and after click on minutes the picker would automatically close.  I can see that happening on 24 hour mode but not 12 hour mode.  Am I interpreting this property wrong?

**Comment by ecmadao** [comment]
No, `autoMode` only means automatically open picker modal for user, and auto close only support for 24 hours mode. Because I think user usually change time quantum in 12 hours mode, so we shouldn't auto close modal when user selected hour or minute, cause they may also wanna change time quantum.

**Comment by erin-doyle** [comment]
Ah ok, that makes sense.  Thanks for explaining!
