### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by carlodicelico** [ecmadao/react-times#35]
**Story:** As a user, I want to select a timezone so that the time I choose has the correct context.

**Implementation:** A feature flag ( `{ includeTimezone: true }` or similar ), which would "turn on" the timezone feature, resulting in a link below the clock face to choose the timezone. Clicking this link will load a typeahead component that will help users select a timezone based on fuzzy search of IANA timezone data.

**Notes:** In progress! 🤓 🚀

**Comment by ecmadao** [comment]
Cool!

**Comment by carlodicelico** [comment]
@ecmadao sounds good!

**Comment by carlodicelico** [comment]
Nearly there! 

<img width="1680" alt="fullscreen_4_20_17__11_43_am" src="https://cloud.githubusercontent.com/assets/1778532/25239674/a748edbe-25be-11e7-9f71-c7a8fbe358e7.png">

Fuzzy search part is in progress now. 😎

**Comment by ecmadao** [comment]
@carlodicelico 
Cooooooool! Great work!

**Comment by ecmadao** [comment]
New version v2.1.0 publish!
