### ISSUE TITLE
12-hour time not working with defaultTime specified in 24-hour format

### ISSUE THREAD

**Issue by carlodicelico** [ecmadao/react-times#37]
When you specify a time in 24-hour format, it shows up in the 12-hour clock in 24-hour format instead of 12-hour format. I would expect that a time specified in 24-hour format would be reformatted to 12-hour format when the dev uses 12-hour mode. 🤔 So, 13:15 would (I think) be reformatted to 1:15PM. Currently, the picker shows 13:15 AM, which _might_ be possible, _if_ you're Doc Brown or Marty McFly. 😜 

Here's a screenshot showing the issue in the online demo:

<img width="1680" alt="fullscreen_4_20_17__11_38_am" src="https://cloud.githubusercontent.com/assets/1778532/25239467/1041df2a-25be-11e7-87cc-58b97f4ca9b7.png">

**Notes:** Bug label, in progress 🚀

**Comment by ecmadao** [comment]
@carlodicelico 
Pretty cool! Thanks for your help!
