### ISSUE TITLE
12:00 AM and 12:30AM should be 12:00 PM and 12:30PM respectively, in time list

### ISSUE THREAD

**Issue by khushi511** [ecmadao/react-times#38]
Hii, 
The list of time is showing 12.00 am 12.30am instead of 12.00pm and 12.30pm.
below is the screenshot.
![image](https://cloud.githubusercontent.com/assets/10815258/25303809/f21f053e-2777-11e7-9526-6385c2eb31d5.png)

Kindly solve this issue as soon as possible.

Thanks

**Comment by ecmadao** [comment]
@khushi511 
Felt sorry for this bug, I'll fix it right now.

**Comment by ecmadao** [comment]
@khushi511 
V1.4.6 is published and this bug was resolved.
