### ISSUE TITLE
If not set explicitly hours default to 00

### ISSUE THREAD

**Issue by bearoutthere** [ecmadao/react-times#39]
In a field without any time already saved open react-times widget.
- It shows current time (hours and minutes)
- Click on the minutes and set them.  Do not set hours to anything.
After the time is saved to the field the hours are set to 00 rather than the current hours.

Smells like a bug, feels like a bug ;)

**Comment by carlodicelico** [comment]
Thanks for submitting this, @bearoutthere! This issue will be resolved shortly. In a forthcoming PR, the timepicker will default to your current user time.

**Note:** In progress 🚀

**Comment by ecmadao** [comment]
@bearoutthere 
Thanks for your help!
It will be resolved in the following version by @carlodicelico
