### ISSUE TITLE
Meridiem not internationalized consistently

### ISSUE THREAD

**Issue by carlodicelico** [ecmadao/react-times#40]
When you choose a language with cool writing 😎 the meridiem shows up properly in the trigger component but not the timepicker itself.

Here's a screenshot showing the issue in the online demo:

<img width="1277" alt="react_storybook_and_readme_md_ ___source_react-times" src="https://cloud.githubusercontent.com/assets/1778532/25631153/88a23aae-2f3d-11e7-8ed1-e96711c1de9e.png">

**Comment by ecmadao** [comment]
😁  So many thanks. I'll check your PR this night.
@carlodicelico
