### ISSUE TITLE
Question: full time range

### ISSUE THREAD

**Issue by bytewiz** [ecmadao/react-times#48]
Would it be possible to add so the it is not only a 5min snap? so that I could e.g. select a time of e.g. 13:37?

**Comment by ecmadao** [comment]
@bytewiz 
Thanks for your feedback. It seems make sense, so I'll thinking about it and work on it several days later.

**Comment by bytewiz** [comment]
Let me know if want any assistance :+1:

**Comment by ethorz** [comment]
@ecmadao It would be a very necessary thing.

**Comment by ecmadao** [comment]
@bytewiz @ethorz 
Hey, I just support minute picker now. Sorry for let you guys waiting for a long long time.

I add two new props: `minuteStep` and `limitDrag`

- `minuteStep` means the minimum change of minute, default `5`, you can set it to `1` or any other number

- `limitDrag` menus whether limit user's drag or not, default `false`. When `true`, user's drag rotation will be limited.

You can click here to play [online demo](https://ecmadao.github.io/react-times/?selectedKind=Default%20TimePicker&selectedStory=limit%20drag&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

**Comment by norayr93** [comment]
minuteStep doesn't work

**Comment by norayr93** [comment]
Ok , thanks ... me and my friend have noticed a bug ... When you turn arround the pointer to left side , the time doesnt work correctly ... it shows 0-2 : 25 or 08: 0-28

**Comment by ecmadao** [comment]
@norayr93 THX! It is bug, yes. I'm feeling sorry for that. I'll fix it right now.
