### ISSUE TITLE
Set minuteStep for classic theme

### ISSUE THREAD

**Issue by STEVEOO6** [ecmadao/react-times#63]
It would be great if there were a way to set a time more granular than the current 30-minute-intervals listed when using the classic theme. For example, I want user's to be able to select 11:00, 11:10, 11:20, 11:30, 11:40, 11:50, 12:00... etc

One option would be to use the minuteStep prop to calculate the available times.

Another option would be to allow the user to supply an array of the available time options.

**Comment by ecmadao** [comment]
It's cool, but by using this way will render too many times for user to chose. Do you have any more ideas to optimize it?

**Comment by STEVEOO6** [comment]
It could be split so that the user selects the hour before selecting the minute in a separate dropdown, but in my opinion that would be a different component so should fall outside the scope of this component.

For my use case however, I only want to render 15 minute intervals between 7am and 7pm... which is only 48 options and currently the classic theme hardcodes the options listed

**Comment by ecmadao** [comment]
Time render limit #87

**Comment by ecmadao** [comment]
v3.1.3 published.
