### ISSUE TITLE
Update to React 16?

### ISSUE THREAD

**Issue by effinrich** [ecmadao/react-times#67]
Hi,
I'd really like to use react-times in our project, but it's not functioning properly on React 16.  Are you planning an update to React 16 soon?

thanks

**Comment by ecmadao** [comment]
Sorry guys, I wanna update to react 16 too, but I don't have many personal time to refactor. I can create a new branch to do that but can not complete it in recent days. Anyway, thanks a lot for your advice!

**Comment by effinrich** [comment]
Hey, I pulled your repo down and tested with React 16.  No work needed, works out of the box.

thanks!
