### ISSUE TITLE
bug: custom minute setup of minute page

### ISSUE THREAD

**Issue by Nikaple** [ecmadao/react-times#71]
24 -> 12, see pic below:

![qq 20180108144420](https://user-images.githubusercontent.com/24775744/34661178-e54ebc36-f482-11e7-99aa-d2dd09d8a393.png)

**Comment by Nikaple** [comment]
open demo page, select custum minute setup, and **any** 24 min will become 12 min.

**Comment by Nikaple** [comment]
> /src/components/Picker/PickerDragHandler.jsx
```javascript
handleTimePointerChange(){
  //...
  time = time === 24 ? 12 : time;  // should check hour or minute here ?
}
```

**Comment by ecmadao** [comment]
Hey Nikaple, thanks for your feedback! But now I'm trekking in Tibet and Nepal, so I can't fix it until thirty days (even more) later. Anyway, thanks for yourhelp!

**Comment by ecmadao** [comment]
THX! You are quite right. This bug will fixed in next version. @Nikaple

**Comment by ecmadao** [comment]
v3.1.1 published.
