### ISSUE TITLE
Shouldn't meridiem change also call onTimeChange?

### ISSUE THREAD

**Issue by n23daniel** [ecmadao/react-times#76]
Using the timepicker in a redux form field, I'm needing to same the value in an object with time and meridiem keys and call input.onChange() for time and meridiem separately. It would be much less of a hustle to also call onTimeChange when meridiem is changed.

**Comment by ecmadao** [comment]
@n23daniel 
Yeah it's a good advice. Maybe I can combine the `onTimeChanged` and `onMeridiemChange` together on the next version.

**Comment by ecmadao** [comment]
Working on it. #85

**Comment by ecmadao** [comment]
Done in version 3.1.0
