### ISSUE TITLE
not updating hour & minute when changing them

### ISSUE THREAD

**Issue by msman** [ecmadao/react-times#78]
hi

the demo worked, but when I click on hour and minute to select desired time, the current written time above is not updated.
I use creat-react-app, do I need to configure weback json? If so, let me tell you that I don't have that file in my create-react-app. Please help.

**Comment by lazreg87** [comment]
You need to update the time value in the TimePicker, e.g. 

```javascript
class TimePickerWrapper extends Component {
  constructor(props) {
    super(props);
    this.state = {
      time: ''
    };
    this.onTimeChange = this.onTimeChange.bind(this);
  }

  onTimeChange(time) {
    this.setState({time});
  }

  render() {
    return (
      <TimePicker time={this.state.time} draggable={false} onTimeChange={this.onTimeChange} theme="classic"/>
    );
  }
}
```

**Comment by ecmadao** [comment]
@msman 
Yes, as @lazreg87 said, you need save hour/minute/meridiem as state.
Besides, `onHourChange`/`onMinuteChange`/`onMeridiemChange` props were abandon now (since v3.1.0), just use `onTimeChange` instead.
