### ISSUE TITLE
onTimeChange not works when meridiem changes

### ISSUE THREAD

**Issue by vsamotskiy** [ecmadao/react-times#82]
When we change meridiem in **timeMode="12"** onTimeChange callback is not called. When we change time in the same 12 hours mode value passed to onTimeChange callback without meridiem. Hope it will be fixed asap.  Thanks

**Comment by elboletaire** [comment]
May be dup of #76

**Comment by ecmadao** [comment]
Working on it. #85

**Comment by ecmadao** [comment]
Done in version 3.1.0
