### ISSUE TITLE
json-loader not needed in webpack@4

### ISSUE THREAD

**Issue by kaspermarkus** [ecmadao/react-times#86]
I got the following error when following the instructions from the README.md:

>  ERROR in ./node_modules/moment-timezone/data/packed/latest.json
> Module parse failed: Unexpected token m in JSON at position 0
> You may need an appropriate loader to handle this file type.

It turns out that webpack@4 automatically loads json files and hence the json-loader is not needed (I found out here https://github.com/webpack-contrib/file-loader/issues/259). The solution was to ignore the json-loader instructions from the README.md and things were working as expected. I suggest this should be mentioned in the README

**Comment by ecmadao** [comment]
@kaspermarkus 
Yes, you are right. Some users may don't need to install json-loader. I'll change README ASAP. Thanks for your feedback!
