### ISSUE TITLE
Double triggering onTimeChange in the repeated selection of the same hour

### ISSUE THREAD

**Issue by Kerenby74** [ecmadao/react-times#89]
Good afternoon, like your watch, but it's impossible to work with them because of double triggering onTimeChange at the repeated choice of the hour, as before, I would be very grateful if you could solve this problem. P.S only mobile version

**Comment by ecmadao** [comment]
Thanks for your feedback! Actually I have never test it on mobile before. Can you give me more detail about it?

For example, are you trying to drag the pointer to change hour/minute, or just click the number? And what do you mean by saying `repeated choice of the hour`?

Thanks!

**Comment by Kerenby74** [comment]
When you click on the screen, if you have already selected an hour, after selecting an hour, you can not select a minute anymore, because The state overwrites twice and visibility is turned off. This is only in the mobile version of the browser, I checked into Google Chrome.

Here's the link to the video : https://youtu.be/LoO-wnJMT6M

**Comment by ecmadao** [comment]
Okey I got it. Seems you wanna create two time picker like:

```javascript
<TimePicker />
<TimePicker />
```

Right? I'll check this issue today.

**Comment by ecmadao** [comment]
I fix this problem and published v3.1.6. You can also check the example for usage: https://github.com/ecmadao/react-times/blob/master/examples/TimePickerWrapper2.js

Thanks for your feedback!
@Kerenby74
