### ISSUE TITLE
Focus to the default time when opening the timepicker. 

### ISSUE THREAD

**Issue by pankaja92** [ecmadao/react-times#92]
How can I set the focus to default time when opening the timepicker

```
 onTimeChange = options => {
        const {
            hour,
            minute,
          } = options;

        console.log(hour);
        console.log(minute);
    }

    render(){
        return (
            <div>
               <TimePicker 
                    theme="classic"
                    time="17:00"
                    onTimeChange={this.onTimeChange}
                    />
            </div>
        )
    }
```

Above is my code. What I want is when opening the timepicker, it should be focused on 17.00 . This code block sets the time as 17.00, but when opening the time picker, it focused on starting point ( 00.00 ). How can I set this ?

**Comment by ecmadao** [comment]
Yes, it should be focused on "17:00", and your code worked for me. And you check your `react-times` version?
