### ISSUE TITLE
Center screen on mobile

### ISSUE THREAD

**Issue by Altiano** [ecmadao/react-times#96]
How about something like this on mobile (small viewport)?

![image](https://user-images.githubusercontent.com/8316282/43989331-703339d0-9d7a-11e8-8237-5e29f8898a76.png)

**Comment by ecmadao** [comment]
@Altiano 
Yeah thanks for your advice! Actually I also have plan to add an mobile version, or directly change the whole UI. But I'm traveling in Japan these days so may can not working on it until September. Anyway, thanks again!

**Comment by Altiano** [comment]
Looking forward for this.
Great work anyway.
